# Generated by Django 2.0.3 on 2018-04-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='analysis_type',
            field=models.IntegerField(default=0),
        ),
    ]
